version = 0.1
[default.deploy.parameters]
stack_name = "prometheus-test-stack"
resolve_s3 = true
s3_prefix = "prometheus-test-stack"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
