AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  v-btwin

  Sample SAM Template for v-btwin

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 40
    MemorySize: 128

    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  MeterReadingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: meter_reading/
      Handler: meter-reading-api.createMeterReadings
      Runtime: nodejs16.x
      Architectures:
      - x86_64
      Events:
        createMeterReading:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /create-meter-readings
            Method: post

  MetricsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: meter_reading/
      Handler: meter-reading-api.getMetrics
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        getMetrics:
          Type: Api
          Properties:
            Path: /metrics
            Method: get

  createBuildingReadingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: meter_reading/
      Handler: meter-reading-api.createBuildingReadings 
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        getMetrics:
          Type: Api
          Properties:
            Path: /create-building-readings
            Method: post
# Outputs:
  
#   HelloWorldApi:
#     Description: API Gateway endpoint URL for Prod stage for Hello World function
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
#   HelloWorldFunction:
#     Description: Hello World Lambda Function ARN
#     Value: !GetAtt HelloWorldFunction.Arn
#   HelloWorldFunctionIamRole:
#     Description: Implicit IAM Role created for Hello World function
#     Value: !GetAtt HelloWorldFunctionRole.Arn
